# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.start_Button.setGeometry(QtCore.QRect(440, 80, 75, 31))
        self.start_Button.setObjectName("start_Button")
        self.end_Button = QtWidgets.QPushButton(self.centralwidget)
        self.end_Button.setGeometry(QtCore.QRect(440, 120, 75, 31))
        self.end_Button.setObjectName("end_Button")
        self.pre_Button = QtWidgets.QPushButton(self.centralwidget)
        self.pre_Button.setGeometry(QtCore.QRect(440, 160, 75, 31))
        self.pre_Button.setObjectName("pre_Button")
        self.next_Button = QtWidgets.QPushButton(self.centralwidget)
        self.next_Button.setGeometry(QtCore.QRect(440, 200, 75, 31))
        self.next_Button.setObjectName("next_Button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 501, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.label_3.setObjectName("label_3")
        self.roomlineE = QtWidgets.QLineEdit(self.centralwidget)
        self.roomlineE.setGeometry(QtCore.QRect(110, 70, 141, 31))
        self.roomlineE.setObjectName("roomlineE")
        self.path_lab = QtWidgets.QLabel(self.centralwidget)
        self.path_lab.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.path_lab.setObjectName("path_lab")
        self.path_lineE = QtWidgets.QLineEdit(self.centralwidget)
        self.path_lineE.setGeometry(QtCore.QRect(110, 10, 141, 31))
        self.path_lineE.setObjectName("path_lineE")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 110, 391, 121))
        self.listWidget.setObjectName("listWidget")
        self.list_Button = QtWidgets.QPushButton(self.centralwidget)
        self.list_Button.setGeometry(QtCore.QRect(440, 40, 75, 31))
        self.list_Button.setObjectName("list_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_Button.setText(_translate("MainWindow", "开始捕捉"))
        self.end_Button.setText(_translate("MainWindow", "停止捕捉"))
        self.pre_Button.setText(_translate("MainWindow", "上一个"))
        self.next_Button.setText(_translate("MainWindow", "下一个"))
        self.label_2.setText(_translate("MainWindow", "输出信息："))
        self.label_3.setText(_translate("MainWindow", "直播间房号："))
        self.path_lab.setText(_translate("MainWindow", "保存路径："))
        self.list_Button.setText(_translate("MainWindow", "直播列表"))
